# Generated by Django 5.2 on 2025-06-05 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMainTable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('assigned_tables', models.ManyToManyField(blank=True, related_name='assigned_tables', to='tables.scrumtable')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='scrum_tables', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, related_name='scrum_tables', to='tasks.task')),
            ],
            options={
                'db_table': 'tables_ScrumTable',
            },
        ),
    ]
