# Generated by Django 5.2.2 on 2025-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.TextField(blank=True, help_text='Ссылки на ресурсы проекта (по одной на строку)'),
        ),
    ]
