# Generated by Django 5.2 on 2025-04-27 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.status')),
            ],
        ),
        migrations.CreateModel(
            name='ScrumTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMainTable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('assigned_tables', models.ManyToManyField(blank=True, related_name='assigned_tables', to='tasks.scrumtable')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='scrum_tables', to=settings.AUTH_USER_MODEL)),
                ('Tasks', models.ManyToManyField(blank=True, related_name='scrum_tables', to='tasks.task')),
            ],
        ),
    ]
