# Generated by Django 5.2.2 on 2025-06-09 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Сложность должна быть не менее 1'), django.core.validators.MaxValueValidator(100, message='Сложность должна быть не более 100')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Приоритет должен быть не менее 1'), django.core.validators.MaxValueValidator(100, message='Приоритет должен быть не более 100')]),
        ),
    ]
