# Generated by Django 5.2 on 2025-06-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
